apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: {{.values.restPort}}
    protocol: TCP
    targetPort: {{.values.nodePort}}
  selector:
    app: flaskapi
  type: NodePort