apiVersion: v1
kind: ConfigMap
metadata:
  name: flaskapi-config
  labels:
    app: flaskapi
data:
  FLASK_APP: run.py
  FLASK_DEBUG: "0"
  FLASK_ENV: production
  TESTING: "False"
  DATABASE_URL: {{.values.db-url}}
  SK: yS6xsprA0gTuBWO_vV2JVQ
  SEND_FILE_MAX_AGE_DEFAULT: "31556926"
  BCRYPT_LOG_ROUNDS: "13"
  DEBUG_TB_ENABLED: "False"
  DEBUG_TB_INTERCEPT_REDIRECTS: "False"
  CACHE_TYPE: simple
  SQLALCHEMY_TRACK_MODIFICATIONS: "False"
  CSRF_ENABLED: "True"
  RESTPLUS_MASK_SWAGGER: "False"