---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: miltex/python-api:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: flaskapi-config
          env:
            - name: REST_IP
              value: {.values.restIP}
            - name: REST_PORT
              value: {.values.restPort}
            - name: MDB_IP
              value: {.values.mdbIP}
            - name: MDB_PORT
              value: {.values.mdbPort}  
            - name: MDB_USER
              value: {.values.mdbUser}
            - name: MDB_PASSWORD
              value: {.values.mdbPw}  